### ISSUE TITLE
Mam pytanie:

### ISSUE THREAD

**Issue by NoHomoMen** [Inder00/Drop#3]
Jakie external archives miałeś bo chce dodać tego turboexp'a i jeszcze kilka rzeczy ale nie mam czasu poszukać, na dysku posiadam spigot'a i craftbukkit'a 1.8.8, ale widze że się pyta o coś jeszcze, (a tak zaawansowanym programistą nie jestem żeby się domyślić z import'u) pod jakie wersje lub na jakich pisałeś plugin? lub czy jest potrzebny jakiś lib,api ?

**Comment by Inder00** [comment]
czysty spitgot
